/**
 * 아이콘 단일 출처 (lucide-react).
 *
 * 왜 이 파일이 있나:
 *  1. 레퍼런스 §4.1 — "메뉴 아이콘은 **동일 라이브러리**의 18~20px 선형 아이콘.
 *     이모지와 선형 아이콘을 섞지 않는다." → 한 곳에서만 고른다.
 *  2. 이름을 각 화면에서 직접 import 하면 존재하지 않는 이름을 쓰다 런타임에 깨진다.
 *     여기 있는 이름은 전부 `node -e "require('lucide-react')"` 로 **존재를 실측**했다.
 *
 * ⚠ 구 시제품 `app/(app)/**` 와 `components/{dashboard,order,customer,...}` 는
 *    동결본이라 `@tabler/icons-react` 를 그대로 쓴다. 두 팩이 병존하는 건 의도된 상태다.
 *    신규 화면에서는 **이 파일만** 쓴다.
 *
 * 크기 규약(레퍼런스 §4.1·§4.2):
 *   메뉴/본문 18px · 상단바 아이콘버튼 18~20px · 배지/인라인 14px · 빈상태 28~32px
 *   `strokeWidth` 는 lucide 기본 2 를 쓰되, 18px 이하에서 두꺼워 보이면 1.75 로 낮춘다.
 */
import {
  // 셸·네비게이션
  LayoutDashboard,
  CalendarDays,
  Users,
  Package,
  ClipboardList,
  Boxes,
  Wrench,
  ScanLine,
  Receipt,
  UserCog,
  Settings,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  LogOut,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Search,
  Bell,
  Plus,
  // 업종
  Factory,
  Shirt,
  Store,
  Scissors,
  School,
  // 상태·피드백
  Check,
  CheckCircle2,
  X,
  AlertTriangle,
  Info,
  CircleAlert,
  TriangleAlert,
  Loader2,
  // 추세
  TrendingUp,
  TrendingDown,
  Minus,
  // 폼·인증
  Mail,
  Lock,
  Eye,
  EyeOff,
  User,
  // 업무
  Printer,
  QrCode,
  Barcode,
  Camera,
  Filter,
  ArrowRight,
  ArrowUpRight,
  ExternalLink,
  Clock,
  MapPin,
  Ruler,
  Palette,
  CircleDot,
  Pencil,
  Trash2,
  RotateCcw,
  Download,
  Upload,
  Sun,
  Moon,
  FileText,
  CircleUserRound,
  ClipboardCheck,
  CalendarClock,
  BookOpen,
  Banknote,
  // 신규 화면 이전분(Tabler → lucide, R4)
  Undo2,
  Redo2,
  ArrowLeft,
  Ban,
  Building2,
  CalendarCheck2,
  CalendarPlus,
  CalendarRange,
  CameraOff,
  ListChecks,
  CircleX,
  ClipboardPlus,
  Clock4,
  Play,
  StopCircle,
  Columns2,
  FilterX,
  HelpCircle,
  History,
  Inbox,
  KeyRound,
  MailCheck,
  MailQuestion,
  PackagePlus,
  RefreshCw,
  Repeat,
  Truck,
  UserPlus,
  Video,
  ZoomIn,
  ZoomOut,
  Circle,
  // 문구 보내기/키오스크(0023 UI 연결)
  Copy,
  Share2,
  MessageSquare,
  Phone,
  Send,
  Delete,
} from "lucide-react";

export {
  LayoutDashboard,
  CalendarDays,
  Users,
  Package,
  ClipboardList,
  Boxes,
  Wrench,
  ScanLine,
  Receipt,
  UserCog,
  Settings,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  LogOut,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Search,
  Bell,
  Plus,
  Factory,
  Shirt,
  Store,
  Scissors,
  School,
  Check,
  CheckCircle2,
  X,
  AlertTriangle,
  Info,
  CircleAlert,
  TriangleAlert,
  Loader2,
  TrendingUp,
  TrendingDown,
  Minus,
  Mail,
  Lock,
  Eye,
  EyeOff,
  User,
  Printer,
  QrCode,
  Barcode,
  Camera,
  Filter,
  ArrowRight,
  ArrowUpRight,
  ExternalLink,
  Clock,
  MapPin,
  Ruler,
  Palette,
  CircleDot,
  Pencil,
  Trash2,
  RotateCcw,
  Download,
  Upload,
  Sun,
  Moon,
  FileText,
  CircleUserRound,
  ClipboardCheck,
  CalendarClock,
  BookOpen,
  Banknote,
  Undo2,
  Redo2,
  ArrowLeft,
  Ban,
  Building2,
  CalendarCheck2,
  CalendarPlus,
  CalendarRange,
  CameraOff,
  ListChecks,
  CircleX,
  ClipboardPlus,
  Clock4,
  Play,
  StopCircle,
  Columns2,
  FilterX,
  HelpCircle,
  History,
  Inbox,
  KeyRound,
  MailCheck,
  MailQuestion,
  PackagePlus,
  RefreshCw,
  Repeat,
  Truck,
  UserPlus,
  Video,
  ZoomIn,
  ZoomOut,
  Circle,
  Copy,
  Share2,
  MessageSquare,
  Phone,
  Send,
  Delete,
};

/** 업종 → 아이콘. `lib/industry/config.ts` 의 `icon` 문자열이 Tabler 이름이라 여기서 변환한다. */
export const INDUSTRY_ICON = {
  factory: Factory,
  rental: Shirt, // lucide 에 Hanger 가 없다(실측). 의류 = Shirt 가 가장 가깝다.
  unmanned: Store,
  salon: Scissors,
  academy: School,
} as const;

/** 알 수 없는 업종 키로 떨어질 때의 대체 아이콘. */
export const FALLBACK_ICON = Building2;

/**
 * 메뉴 key → 아이콘.
 * `lib/industry/config.ts` 의 `nav[].key` 와 1:1. 새 메뉴를 넣으면 여기도 채운다
 * (없으면 `CircleDot` 로 떨어져 눈에 띈다 — 조용히 빈 자리로 두지 않는다).
 */
export const NAV_ICON: Record<string, typeof LayoutDashboard> = {
  dash: LayoutDashboard,
  calendar: CalendarDays,
  customers: Users,
  orders: ClipboardList,
  production: Wrench,
  materials: Boxes,
  reservations: CalendarClock,
  catalog: Package,
  care: Wrench,
  scan: ScanLine,
  settlement: Receipt,
  staff: UserCog,
  products: Package,
  stock: Boxes,
  tasks: ClipboardCheck,
  sales: Banknote,
  services: Scissors,
  "staff-shift": Clock,
  students: Users,
  consultations: UserPlus,
  classes: BookOpen,
  timetable: CalendarDays,
  attendance: ClipboardCheck,
  tuition: Banknote,
  settings: Settings,
};

export const navIcon = (key: string) => NAV_ICON[key] ?? CircleDot;

/** 상태 → 아이콘. 색만으로 상태를 전달하지 않기 위한 짝(§5.3·dataviz). */
export const STATUS_ICON = {
  ok: CheckCircle2,
  warn: TriangleAlert,
  error: CircleAlert,
  info: Info,
} as const;

/** 레퍼런스 §4.1 기준 크기. 임의 px 을 흩뿌리지 않는다. */
export const ICON_SIZE = {
  nav: 18,
  topbar: 18,
  inline: 14,
  empty: 30,
} as const;
